config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users
  resources :restaurants
  root 'restaurants#index'
  post 'search' => 'restaurants#search'
  get 'search' => 'restaurants#index'
  get 'vote_history' => 'restaurants#vote_history'
  get 'user_summary' => 'comments#summary'
  patch 'favorite' => 'comments#favorite'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
  validates_presence_of :body
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  validates_presence_of :name, :address, :city
  has_many :user_votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_votes
  has_many :comments
  has_many :favorites
end

app/models/user_vote.rb
class UserVote < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment.restaurant, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def summary
    @comments = Comment.where(user_id: current_user.id)
    @user_votes = UserVote.where(user_id: current_user.id)
    @favorite_restaurants = Favorite.where(user_id: current_user.id, favorite_res: true)
  end

  def favorite
    if current_user.favorites.find_by(restaurant_id: params[:id].to_i)
      current_user.favorites.find_by(restaurant_id: params[:id].to_i).update_column(:favorite_res, params[:checked])
    else
      current_user.favorites.create(restaurant_id: params[:id].to_i, favorite_res: params[:checked])
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:body, :user_id, :restaurant_id)
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:show, :index, :vote_history, :search]
  skip_before_action :verify_authenticity_token
  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
    if current_user
      @comment = Comment.new(user_id: current_user.id, restaurant_id:  @restaurant.id)
      @comments = Comment.where(restaurant_id: @restaurant.id)
    end
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      @restaurant.name = restaurant_params[:name] if restaurant_params[:name]
      @restaurant.address = restaurant_params[:address] if restaurant_params[:address]
      @restaurant.city = restaurant_params[:city] if restaurant_params[:city]
      if @restaurant.save
        create_user_votes
        format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    @restaurants = Restaurant.where("name like ? AND city like ? AND address like ?",
                                    "%#{params['restaurant']['name']}%", "%#{params['restaurant']['city']}%", "%#{params['restaurant']['address']}%")
    respond_to do |format|
      format.html { render :index }
    end
  end

  def vote_history
    @user_votes = UserVote.where(restaurant_id: params[:id].to_i)
  end

  private

  def create_user_votes
    if params[:restaurant][:upvote]
      if current_user.user_votes.find_by(restaurant_id: @restaurant.id)
        current_user.user_votes.find_by(restaurant_id: @restaurant.id).increment!(:upvote)
      else
        current_user.user_votes.create(restaurant_id: @restaurant.id, upvote: 1)
      end
    elsif params[:restaurant][:downvote]
      if current_user.user_votes.find_by(restaurant_id: @restaurant.id)
        current_user.user_votes.find_by(restaurant_id: @restaurant.id).increment!(:downvote)
      else
        current_user.user_votes.create(restaurant_id: @restaurant.id, downvote: 1)
      end
    end
  end
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :city, :upvote, :downvote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: comment, local: true) do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :comment_body %>
  </div>

  <div class="field" style="display: none">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :comment_user_id %>
  </div>

  <div class="field" style="display: none">
    <%= form.label :restaurant_id %>
    <%= form.text_field :restaurant_id, id: :comment_restaurant_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Restaurant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user %></td>
        <td><%= comment.restaurant %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user %>
</p>

<p>
  <strong>Restaurant:</strong>
  <%= @comment.restaurant %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/comments/summary.html.erb
<div class="row">
  <div class="col-sm-8">
    <h1>My Votes</h1>
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>Restaurant Name</th>
        <th>Upvotes</th>
        <th>Downvotes</th>
      </tr>
      </thead>

      <tbody>
      <% @user_votes.each do |vote| %>
          <tr>
            <td><%= link_to vote.restaurant.name, vote.restaurant, class: 'btn btn-sm btn-default' %></td>
            <td><%= vote.upvote.to_i %></td>
            <td><%= vote.downvote.to_i %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  </div>
<div class="row">
  <div class="col-sm-8">
    <h1>My Comments</h1>
    <table class="table table-bordered">
      <thead>
      <tr>
        <th>Restaurant Name</th>
        <th>Comment</th>
      </tr>
      </thead>

      <tbody>
      <% @comments.each do |comment| %>
          <tr>
            <td><%= link_to comment.restaurant.name, comment.restaurant, class: 'btn btn-sm btn-default' %></td>
            <td><%= comment.body %></td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div><div class="row">
  <div class="col-sm-8">
    <h1>My Favorite Restaurants</h1>
    <ul>
      <% @favorite_restaurants.each do |favorite| %>
          <li>
            <%= link_to favorite.restaurant.name, favorite.restaurant %>
          </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SplitTheCheck</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  </head>

  <body>
  <div class="container-fluid">
    <p class="notice" id="flash_notice" style="display: <%= notice ? '' : 'none' %>"><%= notice %></p>
    <p class="alert" id="flash_error" style="display: <%= alert ? '' : 'none' %>"><%= alert %></p>
    <div id="user_nav">
      <% if current_user %>
          Logged in as <span class="text-info"><%= current_user.email %>.</span>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'btn btn-sm btn-default' %>
          <%= link_to "My Summary", user_summary_path, class: 'btn btn-sm btn-warning' %>
      <% else %>
          <%= link_to "Sign up", new_user_registration_path, class: 'btn btn-sm btn-default' %> or
          <%= link_to "log in", new_user_session_path, class: 'btn btn-sm btn-default' %>
      <% end %>
    </div>
    <%= yield %>
  </div>
  </body>
</html>

app/views/restaurants/_comment_index.html.erb
<% if comments.present? %>
    <h1>Comments</h1>

    <table class="table">
      <thead>
      <tr>
        <th>Body</th>
        <th>User Email</th>
      </tr>
      </thead>

      <tbody>
      <% comments.each do |comment| %>
          <tr>
            <td><%= comment.body %></td>
            <td><%= comment.user.email %></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% else %>
<p>No comments record found</p>
<% end %>

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, id: :restaurant_name, class: 'form-control' %>
    </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, id: :restaurant_address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :city %>
    <%= form.text_field :city, id: :restaurant_city, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Save', class: 'btn btn--default' %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<div class="row">
  <div class="col-sm-6">

    <%= render 'form', restaurant: @restaurant %>

    <%= link_to 'Show', @restaurant %> |
    <%= link_to 'Back', restaurants_path %>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>Restaurants</h1>
  </div>
</div>
<div class="row">
  <div class="col-sm-9">
    <%= form_for :restaurant, url: search_path, html: { class: "form-inline" } do |f| %>
        <div class="form-group">
          <%= f.text_field :name, value: params[:restaurant].try(:[], :name), class: 'form-control', placeholder: 'Search by Name' %>
        </div>
        <div class="form-group">
          <%= f.text_field :address, value: params[:restaurant].try(:[], :address), class: 'form-control', placeholder: 'Search by Address' %>
        </div>
        <div class="form-group">
          <%= f.text_field :city, value: params[:restaurant].try(:[], :city), class: 'form-control', placeholder: 'Search by City' %>
        </div>
        <%= f.submit 'Search', class: 'btn btn-default' %>
        <%= link_to 'Reset', restaurants_url, class: 'btn btn-default' %>
    <% end %>
  </div>
  <div class="col-sm-3">
    <%= link_to 'New Restaurant', new_restaurant_path, class: 'btn btn-default pull-right', style: 'margin-top: 14px' %>
  </div>
</div>
<br/>


<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>City</th>
      <% if user_signed_in? %>
          <th>Mark Favorite</th>
          <th>Upvote</th>
          <th>Downvote</th>
    <% end %>
      <th>Up</th>
      <th>DownVote</th>
      <th>Total Votes</th>
      <th>Vote History</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.city %></td>
        <% if user_signed_in? %>
           <td> <%= check_box_tag restaurant.id, restaurant.id,  restaurant.favorites.where(user_id: current_user.id)[0].try(:favorite_res), {id: restaurant.id, class: 'favorite'}  %></td>
            <td><%= button_tag :upvote, value: 'upvote', id: restaurant.id, class: 'upvote btn btn-sm btn-info'  %></td>
            <td><%= button_tag :downvote, value: 'downvote', id: restaurant.id, class: 'downvote  btn btn-sm btn-info'  %></td>
      <% end %>
        <td>
          <span class="up-<%= restaurant.id %>"><%= restaurant.user_votes.sum(:upvote) %></span>
          <td><span class="down-<%= restaurant.id %>"><%= restaurant.user_votes.sum(:downvote) %></span></td>
        <td>
          <span class="<%= restaurant.id %>_total"><%= restaurant.user_votes.sum(:upvote)- restaurant.user_votes.sum(:downvote) %></span>
        </td>
        <td><%= link_to 'History', vote_history_path(id: restaurant), class: 'btn btn-warning btn-sm' %></td>
        <td><%= link_to 'Show', restaurant, class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<script language="JavaScript" type="text/javascript"></script>
<script>
    $(".upvote").click(function () {
      var upvote = $(this).attr("id");
      $.ajax({
        url: 'restaurants/' + $(this).attr("id"),
        type: 'patch',
        data: {'restaurant' : {'upvote' : parseInt($('.' + $(this).attr("id") + '_up').text()) + 1} },
        success: function(data){
          $('.' + upvote + '_up').text(data.upvote);
          $('.' + upvote + '_down').text(data.downvote);
          $('.' + upvote + '_total').text(data.upvote - data.downvote);
        }
      })
    });
    $(".downvote").click(function () {
      var upvote = $(this).attr("id");
      $.ajax({
        url: 'restaurants/' + $(this).attr("id"),
        type: 'patch',
        data: {'restaurant' : {'downvote' : parseInt($('.' + $(this).attr("id") + '_down').text()) + 1 } },
        success: function(data){
          $('.' + upvote + '_up').text(data.upvote);
          $('.' + upvote + '_down').text(data.downvote);
          $('.' + upvote + '_total').text(data.upvote - data.downvote);
        }
      })
    });
    $('.favorite').click(function() {
      var checked;
      if ($(this).is(':checked')) {
        checked = 'true';
      } else {
        checked = 'false';
      }
      $.ajax({
        type: "patch",
        url: "/favorite",
        data: {id: $(this).attr("id"), checked: checked},
        beforeSend: function(){
          $("#flash_notice").text('Loading... Please wait');
          $('#flash_notice').show();
        },
        success: function (data, textStatus) {
          $("#flash_notice").text('Action completed successfully');
          $('#flash_notice').show();
        }
      })
    }
    );
</script>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<div class="row">
  <div class="col-sm-6">

    <%= render 'form', restaurant: @restaurant %>

    <%= link_to 'Back', restaurants_path %>
  </div>
</div>

app/views/restaurants/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @restaurant.city %>
</p>

<p>
  <strong>Upvote:</strong>
<span class="likes"><%= UserVote.where(restaurant_id: @restaurant.id).sum(:upvote) %></span>
</p>

<p>
  <strong>Downvote:</strong>
  <span class="dislikes"><%=  UserVote.where(restaurant_id: @restaurant.id).sum(:downvote)  %></span>
</p>
<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>
<% if user_signed_in? %>

<br>
<br>
<h3>Add new comment</h3>
<%= render 'comments/form', comment: @comment %>
<%= render 'comment_index', comments: @comments %>
<% end %>

app/views/restaurants/vote_history.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>User Votes</h1>
  </div>
</div>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Restaurant Name</th>
      <th>User Email</th>
      <th>Upvotes</th>
      <th>Downvotes</th>
    </tr>
  </thead>

  <tbody>
    <% @user_votes.each do |vote| %>
      <tr>
        <td><%= vote.restaurant.name %></td>
        <td><%= vote.user.email %></td>
        <td><%= vote.upvote.to_i %></td>
        <td><%= vote.downvote.to_i %></td>
      </tr>
    <% end %>
  </tbody>
</table>